# Generated by Django 3.2.8 on 2022-05-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Doubts',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('StudentID', models.CharField(max_length=100, null=True)),
                ('Student_Name', models.CharField(max_length=100, null=True)),
                ('TeacherID', models.CharField(max_length=100, null=True)),
                ('Teacher_Name', models.CharField(max_length=100, null=True)),
                ('Question', models.CharField(max_length=1000)),
                ('Question_date', models.DateTimeField(null=True)),
                ('Answer', models.CharField(max_length=1000, null=True)),
                ('answer_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
